#!/bin/bash

# 申明一个变量
svn_dir=/home/svn_project/trunk

#进入到目录中
cd $svn_dir
#提交
svn up
#使用mvn package进行编译、打包
mvn -Dmaven.test.skip=true clean package

#进入到目录
cd /opt/hms/releases
#删除所有文件夹
rm -rf *
#进入文件夹
cd $svn_dir/target
#解压出 nmd.tar.gz包 中所有的文件
tar xf ./nmd.tar.gz -C /opt/hms/releases/

#删除 即使原档案属性设为唯读，亦直接删除，无需逐一确认。
rm -f /opt/hms/current
#创建符号链接（软链接）
ln -s /opt/hms/releases/nmd /opt/hms/current
#删除所有文件夹
rm -rf /opt/hms/current/logs
#创建符号链接（软链接）
ln -s /opt/hms/shared/logs /opt/hms/current/logs
删除所有文件夹
rm -rf /opt/hms/current/var
#创建符号链接（软链接）
ln -s /opt/hms/shared/var /opt/hms/current/var
删除所有文件夹
rm -rf /opt/hms/current/run
#创建符号链接（软链接）
ln -s /opt/hms/shared/run /opt/hms/current/run

chmod +x /opt/hms/current/bin/*.sh
/opt/hms/current/bin/stop.sh
/opt/hms/current/bin/start.sh
#/opt/hms/current/bin/stop_task.sh
#/opt/hms/current/bin/start_task.sh

注意
(1)
mvn -Dmaven.test.skip=true clean package
两个参数
-DskipTests，不执行测试用例，但编译测试用例类生成相应的class文件至target/test-classes下。
-Dmaven.test.skip=true，不执行测试用例，也不编译测试用例类。
(2)
软链接 Symbolic Link
ln - s
和Windows下的快捷方式一样

硬链接  Hard Link
不加 -s参数
在同一分区下建立的数据关联
(3)
chmod
系统管理员用于改变文件或目录的访问权限

+：添加某个权限
-：取消某个权限
=：赋予给定的权限，并取消原有的权限

权限说明
u User，即文件或目录的拥有者；
g Group，即文件或目录的所属群组；
o Other，除了文件或目录拥有者或所属群组之外，其他用户皆属于这个范围；
a All，即全部的用户，包含拥有者，所属群组以及其他用户；
r 读取权限，数字代号为“4”;
w 写入权限，数字代号为“2”；
x 执行或切换权限，数字代号为“1”；
- 不具任何权限，数字代号为“0”；
s 特殊功能说明：变更文件或目录的权限。


